### ISSUE TITLE
Clicking browser back button after order placed can result in order being deleted

### ISSUE THREAD

**Issue by andrewkett** [Laybuy/Magento-1#3]
## Preconditions

- Magento 1.9.2.0
- PHP 5.6.34
- Latest version of Laybuy extension (0.1.0)

## Steps to reproduce

1. Place order in Magento with Laybuy payment method
2. Complete Laybuy payment information 
3. Finish payment and return to Magento order confirmation page
4. Click browser back button to return to Laybuy
5. On Laybuy error page click the button to return to Magento

## Expected behaviour

Unsure, maybe a Magento error page or a page saying the payment has already been processed

## Actual behaviour

The second time the user returns to Magento the response contains an error, therefore the order is deleted from Magento. The initial payment remains in Laybuy but it no longer has a matching order in Magento.

**Comment by andrewkett** [comment]
In a bit more detail, we are seeing two requests to the /laybuypayments/payment/response/ controller with the same tokens. The first has a success status, e.g:

 /laybuypayments/payment/response/?status=SUCCESS&token=nottherealtoken

However we also see a second request just after which has an error status, e.g:

 /laybuypayments/payment/response/?status=ERROR&token=nottherealtoken

The problem lies in Laybuy_Payments_PaymentController::responseAction as the default behaviour if the response is not SUCCESS or CANCELLED is to delete the order. After the first success response comes back the order is moved from pending to processing which is expected behaviour. So perhaps a viable solution would be to only delete the order if is in pending state, I can't really think of a scenario where we would want to delete a processing order.

There may be other ways to replicate this but the only way I have been able to do it is by following the steps mentioned above.

**Comment by tina-trenkner** [comment]
Update as of September 3. Customer is able to delete his/her order from Magento.  

Preconditions
Magento 1.9.2.0
Latest version of Laybuy extension (1.1.4)

Steps to reproduce
-Place order in Magento with Laybuy payment method
-Start Laybuy payment process
-Click "Return to Merchant"
-At vendor checkout page, select Laybuy as payment, and submit order. Verify order is in Magento.
-Start Laybuy payment process again. 
-Complete Laybuy payment process
-Arrive at vendor success page.
-Click back on browser, see Laybuy error page.
-Click back on browser, see vendor checkout page.
-Click back on browser, see Laybuy error page with what looks like an error code
-Click "return to merchant"
-Get error message at checkout that Laybuy payment is cancelled. In Magento admin, order disappears. 

Expected behaviour
Unsure, maybe a Magento error page or a page saying the payment has already been processed

Actual behaviour
The second time the user returns to Magento the response contains an error, therefore the order is deleted from Magento. The initial payment remains in Laybuy but it no longer has a matching order in Magento.

**Comment by nikolai-overdose** [comment]
Hi @tina-trenkner / @andrewkett;

Nice to meet you guys. We are the new partner looking after this extension.
Thanks for the detailed error reports. We will take a look at the above issue and provide a fix.

Cheers
